name: R Package CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1'

    - name: Install dependencies
      run: |
        R -e 'install.packages("remotes")'
        R -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Check package
      run: R CMD check .
